version: "3"

volumes:
  traefik: null
  db-data: null
  db-backups: null
  minio-data: null

services:
  traefik:
    build:
      context: .
      dockerfile: ./docker/production/traefik/Dockerfile
    image: traefik
    depends_on:
      - django
    volumes:
      - traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:9001:9001"

  django: &django
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    image: django
    container_name: django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - ./geodata:/qgis:z
    env_file:
      - .env
    command: /start

  postgres:
    image: kartoza/postgis:${POSTGRES_MAJOR_VERSION}-${POSTGIS_MAJOR_VERSION}.${POSTGIS_MINOR_RELEASE}
    volumes:
      - db-data:/var/lib/postgresql
      - db-backups:/backups
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: "exit 0"

  dbbackups:
    image: kartoza/pg-backup:${POSTGRES_MAJOR_VERSION}-${POSTGIS_MAJOR_VERSION}.${POSTGIS_MINOR_RELEASE}
    hostname: pg-backups
    volumes:
      - db-backups:/backups
    environment:
      - DUMPPREFIX=PG_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_PORT=${POSTGRES_SERVICE_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DBNAME=${POSTGRES_DB}
      - REMOVE_BEFORE=30
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:6
    container_name: redis

    # can't replicate from named upstream
  celeryworker-1:
    <<: *django
    image: celeryworker-1
    container_name: celeryworker-1
    depends_on:
      - redis
      - postgres
    volumes:
      - ./geodata:/qgis:z
    command: /start-celeryworker
  celeryworker-2:
    <<: *django
    image: celeryworker-2
    container_name: celeryworker-2
    depends_on:
      - redis
      - postgres
    volumes:
      - ./geodata:/qgis:z
    command: /start-celeryworker
  celeryworker-3:
    <<: *django
    image: celeryworker-3
    container_name: celeryworker-3
    depends_on:
      - redis
      - postgres
    volumes:
      - ./geodata:/qgis:z
    command: /start-celeryworker
  celeryworker-4:
    <<: *django
    image: celeryworker-4
    container_name: celeryworker-4
    depends_on:
      - redis
      - postgres
    volumes:
      - ./geodata:/qgis:z
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres
      - django
    command: /start-celerybeat
    restart: unless-stopped

  flower:
    <<: *django
    image: flower
    container_name: flower
    depends_on:
      - celerybeat
    command: /start-flower

  minio:
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=${DJANGO_AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${DJANGO_AWS_SECRET_ACCESS_KEY}
    entrypoint: /bin/bash
    command: -c 'minio server /data --console-address ":9001"'
    volumes:
      - minio-data:/data
